ui = fluidPage(theme = teachingApps::add_theme(getShinyOption("theme")), 
               teachingApps::add_css(),
 
sidebarLayout(
   sidebarPanel(width = 3, 
      sliderInput("shape1", 
                  label = HTML("Shape Parameter (&alpha;)"),
                  min = .5, 
                  max = 10, 
                  step = .5, 
                  value = 2,
                  animate = TRUE),
      sliderInput("shape2", 
                  label = HTML("Shape Parameter (&beta;)"),
                  min = .5, 
                  max = 10, 
                  step = .5,
                  value = .5),
      sliderInput("scale.beta", 
                  label = "Scale Parameter (d)",
                  min = 1, 
                  max = 20, 
                  step = 1, 
                  value = 1,
                  animate = TRUE),
      sliderInput("loc.beta", 
                  label = "Location Parameter (c)",
                  min = 0, 
                  max = 10, 
                  step = .5, 
                  value = 0,
                  animate = TRUE)), 

   mainPanel(width = 9, 
       tabsetPanel(type = "pills", 
             tabPanel("Distribution Function", 
                      metricsgraphicsOutput("betaC", height = "600px")), 
             tabPanel("Mass",
                      metricsgraphicsOutput("betaP", height = "600px")), 
             tabPanel("Survival", 
                      metricsgraphicsOutput("betaR", height = "600px")), 
             tabPanel("Hazard", 
                      metricsgraphicsOutput("betah", height = "600px")), 
             tabPanel("Cumulative Hazard", 
                      metricsgraphicsOutput("betaH", height = "600px")),
             tabPanel("Quantile", 
                      metricsgraphicsOutput("betaQ", height = "600px"))))))
