---
output: html_document
---

### Example 1.5 - Heat Exchanger Tube Crack Data (Meeker & Escobar, 1996)

- Motivation for the study

    + Nuclear power plants use heat exchangers to transfer energy from the reactor to the steam turbines

    + Heat exchangers can contain thousands of tubes to transfer steam 

    + As result of continuous exposure to steam and pressure, the tubes can develop cracks

    + If the cracks grow large enough, a catastrophic failure could occur

    + Tubes are periodically inspected (nondestructive) for cracks

    + If a crack is found that tube is sealed off and no longer used

    + Once a certain number of tubes have been sealed, the entire heat exchanger must be replaced

- Study objectives

    + Engineers what to estimate the service life of the tubes at three nuclear power plants

    + Only a sample of the tubes at each nuclear power plant (100) can be inspected

    + If the from all three plants could be combined a better estimate of the the service life could be found

    + The data can only be combined if the tubes came from a similar manufacturing process and were used under similar conditions
    
- Data set `heatexchanger`

    + The data are inspection results from 300 heat exchanger tubes across three geographically separated plants

    + The observations are right, left and interval censored since each plant began operating one year apart 

    + Across the 300 tubes inspected, 11 were found to have cracks of sufficient length to be sealed off
