ui = fluidPage(theme = teachingApps::add_theme(getShinyOption("theme")), 
               teachingApps::add_css(),

sidebarLayout(
  sidebarPanel(width = 3, 
  hr(),
  sliderInput("range.gamma", 
              label = "Range",
              min =  0, 
              max = 50, 
              value = c(0,25)), 
  hr(),
  sliderInput("theta", 
              label = HTML("Scale Parameter &theta;",
              min = .25, 
              max = 4, 
              step = .25, 
              value = .5, 
              animate = TRUE), 
  hr(),
  sliderInput("kappa",
              label = HTML("Shape Parameter &kappa;",
              min = .25, 
              max = 15, 
              step = .25, 
              value = 1,
              animate = TRUE)),
mainPanel(width = 9,
 tabsetPanel(type = 'pills',
  tabPanel('Distribution Function',
           metricsgraphicsOutput("gammaC",height = "600px")),
  tabPanel('Density',
           metricsgraphicsOutput("gammaP",height = "600px")),
  tabPanel('Survival',
           metricsgraphicsOutput("gammaR",height = "600px")),
  tabPanel('Hazard',
           metricsgraphicsOutput("gammah",height = "600px")),
  tabPanel('Cumulative Hazard',
           metricsgraphicsOutput("gammaH",height = "600px")),
  tabPanel('Quantile',
           metricsgraphicsOutput("gammaQ",height = "600px"))))))
