ui = fluidPage(theme = teachingApps::add_themes(getShinyOption("theme")), 
               teachingApps::add_styles(),

sidebarLayout(
  sidebarPanel(width = 3, 
  hr(),
  sliderInput("range.gamma", 
              label = h2("Range"),
              min =  0, 
              max = 50, 
              value = c(0,25)), hr(),
  sliderInput("theta", 
              label = h2(HTML("Scale Parameter &theta;")),
              min = .25, 
              max = 4, 
              step = .25, 
              value = .5, 
              animate = TRUE), hr(),
  sliderInput("kappa",
              label = h2(HTML("Shape Parameter &kappa;")),
              min = .25, 
              max = 15, 
              step = .25, 
              value = 1,
              animate = TRUE)),
mainPanel(width = 9,
 tabsetPanel(type = 'pills',
  tabPanel(h4('Distribution Function'),metricsgraphicsOutput("gammaC",height = "600px")),
  tabPanel(h4('Density'),              metricsgraphicsOutput("gammaP",height = "600px")),
  tabPanel(h4('Survival'),             metricsgraphicsOutput("gammaR",height = "600px")),
  tabPanel(h4('Hazard'),               metricsgraphicsOutput("gammah",height = "600px")),
  tabPanel(h4('Cumulative Hazard'),    metricsgraphicsOutput("gammaH",height = "600px")),
  tabPanel(h4('Quantile'),             metricsgraphicsOutput("gammaQ",height = "600px"))))))
