ui = fluidPage(theme = teachingApps::add_theme(getShinyOption("theme")), 
               teachingApps::add_style(),
               
sidebarLayout(
  sidebarPanel(width = 3,
    sliderInput("rangegoma", 
                label = h2("Range"),
                min = 0, 
                max = 50, 
                value = c(0,20)),
    sliderInput("th.goma", 
                label = h2(HTML("Scale (&theta;)")),
                min = 0.5, 
                max = 10, 
                step = 0.5, 
                value = 1, 
                animate = TRUE),
    sliderInput("ze.goma", 
                label = h2(HTML("Shape 1 (&zeta;)")),
                min = 0.5, 
                max = 10, 
                step = 0.5, 
                value = 1, 
                animate = TRUE),
    sliderInput("et.goma", 
                label = h2(HTML("Shape 2 (&eta;)")),
                min = 0.5, 
                max = 10, 
                step = 0.5, 
                value = 1,
                animate = TRUE)),

  mainPanel(width = 9,
 tabsetPanel(type = 'pills',
  tabPanel(h4('Distribution Function'),
           metricsgraphicsOutput("gomaC",height = "600px")),
  tabPanel(h4('Density'),              
           metricsgraphicsOutput("gomaP",height = "600px")),
  tabPanel(h4('Survival'),             
           metricsgraphicsOutput("gomaR",height = "600px")),
  tabPanel(h4('Hazard'),               
           metricsgraphicsOutput("gomah",height = "600px")),
  tabPanel(h4('Cumulative Hazard'),    
           metricsgraphicsOutput("gomaH",height = "600px")),
  tabPanel(h4('Quantile'),             
           metricsgraphicsOutput("gomaQ",height = "600px"))))))
