library(teachingApps)
library('plotly')

ui = navbarPage(title = 'Acceptance Testing (Proportions)',
                collapsible = T, 
                position = 'fixed-top',
                theme = shinythemes::shinytheme(theme = getShinyOption("theme")),
                header = tags$head(includeCSS(getShinyOption("css"))),
                footer = HTML(teachingApps::teachingApp(getShinyOption("appName"))),
          
tabPanel(h4('Test For Proportions'),
         sidebarLayout(
           sidebarPanel(width = 3,
             sliderInput('sss', h4('Sample Size'), 
                          min = 5, 
                          max = 30, 
                          step = 1, 
                          value = 10),
             sliderInput('fails2', h4('Failures Allowed'), 
                          min = 0, 
                          max = 10, 
                          step = 1, 
                          value = 1),
             sliderInput('thresh2', h4('Threshold Proportion'), 
                          min = .05, 
                          max = 1, 
                          step = .05, 
                          value = .1),
             sliderInput('objective2', h4('Objective Proportion'), 
                          min = .15, 
                          max = 1, 
                          step = .05, 
                          value = .3),
             sliderInput('contract2', h4('Contract Proportion'), 
                          min = .25, 
                          max = 1, 
                          step = .05, 
                          value = .5)),
           mainPanel(plotlyOutput('prop', height = '650px'),width = 9))))
