ui = navbarPage(title = 'Acceptance Testing (Proportions)',
                collapsible = T, 
                position = 'fixed-top',
                theme  = add_theme(getShinyOption('theme')),
                header = add_css(),
                footer = add_logo(),

tabPanel('Test For Proportions',
         sidebarLayout(
           sidebarPanel(width = 3,
             sliderInput('sss', 
                         'Sample Size', 
                          min = 5, 
                          max = 30, 
                          step = 1, 
                          value = 10),
             sliderInput('fails2', 
                         'Failures Allowed', 
                          min = 0, 
                          max = 10, 
                          step = 1, 
                          value = 1),
             sliderInput('thresh2', 
                         'Threshold Proportion', 
                          min = .05, 
                          max = 1, 
                          step = .05, 
                          value = .1),
             sliderInput('objective2', 
                         'Objective Proportion', 
                          min = .15, 
                          max = 1, 
                          step = .05, 
                          value = .3),
             sliderInput('contract2', 
                         'Contract Proportion', 
                          min = .25, 
                          max = 1, 
                          step = .05, 
                          value = .5)),
           mainPanel(plotlyOutput('prop', height = '650px'),width = 9))))
