ui = fluidPage(theme = teachingApps::add_theme(getShinyOption("theme")), 
               teachingApps::add_css(),

tabPanel('Shiny App',
sidebarLayout(
sidebarPanel(width = 3, 
             hr(),
  sliderInput("rangee", 
              label = "Range:",
              min = 0, 
              max = 50, 
              value = c(0,20)),
  hr(),
  sliderInput("theta", 
              label = HTML("Scale (&theta;)"),
              min = .5, 
              max = 10, 
              step = .5, 
              value = 1, 
              animate = T),
  hr(),
  sliderInput("gamma", 
              label = HTML("Location (&gamma;)"),
              min = 0, 
              max = 15, 
              step = 1, 
              value = 0, 
              animate = T)),

  mainPanel(width = 9,
 tabsetPanel(type = 'pills',
  tabPanel('Distribution Function',  
           metricsgraphicsOutput("expC",height = "600px")),
  tabPanel('Density',
           metricsgraphicsOutput("expP",height = "600px")),
  tabPanel('Survival',
           metricsgraphicsOutput("expR",height = "600px")),
  tabPanel('Hazard',
           metricsgraphicsOutput("exph",height = "600px")),
  tabPanel('Cumulative Hazard',
           metricsgraphicsOutput("expH",height = "600px")),
  tabPanel('Quantile',
           metricsgraphicsOutput("expQ",height = "600px")))))))
