---
title: "Vignette Title"
author: "Vignette Author"
date: "`r Sys.Date()`"
output: 
  rmarkdown::html_vignette:
    css: my-vignette.css
    fig_caption: yes
vignette: >
  %\VignetteIndexEntry{teachingApps-overview}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

teachingApps is a soon-to-be-published software package for crowd-sourcing the creation of math & stats-based web apps. The goal of the package is to make teaching and learning complex math/stats concepts really fast and really easy.

In this talk Maj Jason Freels (ENV) presents some of the 135 apps that have already been built into the package and outlines how these apps can be used to:
 
A) Present four layers of information simultaneously:

    1) Math/Stats concepts through interactive visualizations

    2) Computer programming skills - with R (Python coming soon)

    3) LaTeX equation typesetting with <a target=' ' href='https://www.mathjax.org/'><b>MathJax</b></a>

    4) App development using HTML5, CSS3, and <a target=' ' href='http://shiny.rstudio.com/'><b>Shiny</b></a><br/>

B) Integrate into existing lecture materials (in-res & distance learning)

    + PowerPoint/Prezi/Keynote presentations

    + PDF/Beamer presentations

    + HTML presentations

    + Video Presentations

C) Combine teaching materials from SME's

    + Text

    + Equations

    + Images/Videos

    + Code

    + Shiny Apps

D) Ensure math/stat content is presented consistently across courses 

Also a quote using `>`:

> "He who gives up [code] safety for [code] speed deserves neither."
([via](https://twitter.com/hadleywickham/status/504368538874703872))
