ui = fluidPage(theme = teachingApps::add_theme(getShinyOption("theme")), 
               teachingApps::add_style(),
               
sidebarLayout(
   sidebarPanel(width = 3,
      hr(),
      sliderInput("rangebisa", 
                  label = "Range",
                  min = 0, 
                  max = 20, 
                  value = c(0,4)),
      hr(),
      sliderInput("be.bisa", 
                  label = HTML("Shape (&beta;)"),
                  min = 0.5, 
                  max = 10, 
                  step = 0.5, 
                  value = 1, 
                  animate = TRUE),
      hr(),
      sliderInput("th.bisa", 
                  label = HTML("Scale (&theta;)"),
                  min = 0.5, 
                  max = 10, 
                  step = 0.5, 
                  value = 1,
                  animate = TRUE)),

  mainPanel(width = 9,
    tabsetPanel(type = 'pills',
      tabPanel('Distribution Function',
               metricsgraphicsOutput("bisaC",height = "600px")),
      tabPanel('Density',              
               metricsgraphicsOutput("bisaP",height = "600px")),
      tabPanel('Survival',
               metricsgraphicsOutput("bisaR",height = "600px")),
      tabPanel('Hazard',
               metricsgraphicsOutput("bisah",height = "600px")),
      tabPanel('Cumulative Hazard',
               metricsgraphicsOutput("bisaH",height = "600px")),
      tabPanel('Quantile',
               metricsgraphicsOutput("bisaQ",height = "600px"))))))
