ui = navbarPage(title = 'Location-Scale Family',
                collapsible = T, 
                position = 'fixed-top',
                theme  = teachingApps::add_theme(getShinyOption('theme')),
                header = teachingApps::add_style(),
                footer = teachingApps::add_stamp(),


tabPanel(h4('Overview'),
         mainPanel(uiOutput('overview'), 
                   class = 'shiny-text-output', 
                   width = 12)),
#############################
  tabPanel(h4('Exponential'),
#############################
fluidRow(
  column(width = 12,
     mainPanel(uiOutput('expfunc'), 
                     class = 'shiny-text-output', width = '100%'))),

fluidRow(
  column(width = 12,
     mainPanel(uiOutput('expprops'), 
                     class = 'shiny-text-output', width = '100%'))),

fluidRow(
  column(width = 12, h3('Interactive Shiny App')),
  column(width = 3,
  sidebarPanel(width = '100%', 
  sliderInput("rangee", 
              label = h2("Range:"),
              min = 0, 
              max = 50, 
              value = c(0,20)),
  hr(),
  sliderInput("theta", 
              label = h2(HTML("Scale (&theta;)")),
              min = .5, 
              max = 10, 
              step = .5, 
              value = 1,
              animate = T),
  hr(),
  sliderInput("gamma", 
              label = h2(HTML("Location (&gamma;)")),
              min = 0, 
              max = 15, 
              step = 1, 
              value = 0,
              animate = T))),

column(width = 9,
    mainPanel(width = '100%', 
tabsetPanel(type = 'pills',
  tabPanel(h4('Distribution Function'),  metricsgraphicsOutput("expC",height = "600px")),
  tabPanel(h4('Density'),                metricsgraphicsOutput("expP",height = "600px")),
  tabPanel(h4('Survival'),               metricsgraphicsOutput("expR",height = "600px")),
  tabPanel(h4('Hazard'),                 metricsgraphicsOutput("exph",height = "600px")),
  tabPanel(h4('Cumulative Hazard'),      metricsgraphicsOutput("expH",height = "600px")),
  tabPanel(h4('Quantile'),               metricsgraphicsOutput("expQ",height = "600px"))))))),

#######################
tabPanel(h4('Normal'),
#######################
fluidRow(
  column(width = 12,
     mainPanel(uiOutput('norfunc'), 
                     class = 'shiny-text-output', width = '100%'))),

fluidRow(
  column(width = 12,
     mainPanel(uiOutput('norprops'), 
                     class = 'shiny-text-output', width = '100%'))),

fluidRow(
  column(width = 12, h3('Interactive Shiny App')),
  column(width = 3,
  sidebarPanel(width = '100%', 
  sliderInput("range.n", 
              label = h2("Range"),
              min = -20, 
              max = 20, 
              value = c(-4,4)),
  hr(),
  sliderInput("mu.n", 
              label = h2(HTML("Mean (&mu;)")),
              min = -3, 
              max = 3, 
              step = 0.5, 
              value = 0,
              animate = T),
  hr(),
  sliderInput("sig.n", 
              label = h2(HTML("Std Dev (&sigma;)")),
              min = 0.5, 
              max = 5, 
              step = 0.5, 
              value = 1,
              animate = T))),

column(width = 9,
    mainPanel(width = '100%', 
tabsetPanel(type = 'pills',
  tabPanel(h4('Distribution Function'),metricsgraphicsOutput("norC",height = "600px")),
  tabPanel(h4('Density'),              metricsgraphicsOutput("norP",height = "600px")),
  tabPanel(h4('Survival'),             metricsgraphicsOutput("norR",height = "600px")),
  tabPanel(h4('Hazard'),               metricsgraphicsOutput("norh",height = "600px")),
  tabPanel(h4('Cumulative Hazard'),    metricsgraphicsOutput("norH",height = "600px")),
  tabPanel(h4('Quantile'),             metricsgraphicsOutput("norQ",height = "600px"))))))),

#######################################
tabPanel(h4('SEV'),
#######################################
fluidRow(
  column(width = 12,
     mainPanel(uiOutput('sevfunc'), 
                     class = 'shiny-text-output', width = '100%'))),

fluidRow(
  column(width = 12,
     mainPanel(uiOutput('sevprops'), 
                     class = 'shiny-text-output', width = '100%'))),

fluidRow(
  column(width = 12, h3('Interactive Shiny App')),
  column(width = 3,
  sidebarPanel(width = '100%', 
  sliderInput("range.s", 
              label = h2("Range"),
              min = -20, 
              max = 20, 
              value = c(-6,6)),
  hr(),
  sliderInput("mu.sev", 
              label = h2(HTML("Mean (&mu;)")),
              min = -3, 
              max = 3, 
              step = 0.5, 
              value = 0,
              animate = T),
  hr(),
  sliderInput("sig.sev", 
              label = h2(HTML("Std Dev (&sigma;)")),
              min = 1, 
              max = 10, 
              step = 0.5, 
              value = 1,
              animate = T))),

column(width = 9,
    mainPanel(width = '100%', 
tabsetPanel(type = 'pills',
  tabPanel(h4('Distribution Function'),  metricsgraphicsOutput("sevC",height = "600px")),
  tabPanel(h4('Density'),                metricsgraphicsOutput("sevP",height = "600px")),
  tabPanel(h4('Survival'),               metricsgraphicsOutput("sevR",height = "600px")),
  tabPanel(h4('Hazard'),                 metricsgraphicsOutput("sevh",height = "600px")),
  tabPanel(h4('Cumulative Hazard'),      metricsgraphicsOutput("sevH",height = "600px")),
  tabPanel(h4('Quantile'),               metricsgraphicsOutput("sevQ",height = "600px"))))))),

######################################
tabPanel(h4('LEV'),
######################################
fluidRow(
  column(width = 12,
     mainPanel(uiOutput('levfunc'), 
                     class = 'shiny-text-output', width = '100%'))),

fluidRow(
  column(width = 12,
     mainPanel(uiOutput('levprops'), 
                     class = 'shiny-text-output', width = '100%'))),

fluidRow(
  column(width = 12, h3('Interactive Shiny App')),
  column(width = 3,
  sidebarPanel(width = '100%', 
  sliderInput("range.lev", 
              label = h2("Range"),
              min = -20, 
              max = 20, 
              value = c(-6,6)),
  hr(),
  sliderInput("mu.lev", 
              label = h2(HTML("Mean (&mu;)")),
              min = -3, 
              max = 3, 
              step = 0.5, 
              value = 0,
              animate = T),
  hr(),
  sliderInput("sig.lev", 
              label = h2(HTML("Std Dev (&sigma;)")),
              min = 1, 
              max = 10, 
              step = 0.5, 
              value = 1,
              animate = T))),

column(width = 9,
    mainPanel(width = '100%', 
tabsetPanel(type = 'pills',
  tabPanel(h4('Distribution Function'),  metricsgraphicsOutput('levC',height = "600px")),
  tabPanel(h4('Density'),                metricsgraphicsOutput('levP',height = "600px")),
  tabPanel(h4('Survival'),               metricsgraphicsOutput('levR',height = "600px")),
  tabPanel(h4('Hazard'),                 metricsgraphicsOutput('levh',height = "600px")),
  tabPanel(h4('Cumulative Hazard'),      metricsgraphicsOutput('levH',height = "600px")),
  tabPanel(h4('Quantile'),               metricsgraphicsOutput('levQ',height = "600px"))))))),

######################################
tabPanel(h4('Logistic'),
######################################
fluidRow(
  column(width = 12,
     mainPanel(uiOutput('logisfunc'), 
                     class = 'shiny-text-output', width = '100%'))),

fluidRow(
  column(width = 12,
     mainPanel(uiOutput('logisprops'), 
                     class = 'shiny-text-output', width = '100%'))),

fluidRow(
  column(width = 12, h3('Interactive Shiny App')),
  column(width = 3,
  sidebarPanel(width = '100%', 
  sliderInput("range.l", 
              label = h2("Range"),
              min = -20, 
              max = 20, 
              value = c(-4,4)),
  hr(),
  sliderInput("mu.l", 
              label = h2(HTML("Mean (&mu;)")),
              min = -3, 
              max = 3, 
              step = 0.5, 
              value = 0,
              animate = T),
  hr(),
  sliderInput("sig.l", 
              label = h2(HTML("Std Dev (&sigma;)")),
              min = 0.5, 
              max = 5, 
              step = 0.5, 
              value = 1,
              animate = T))),

column(width = 9,
    mainPanel(width = '100%', 
tabsetPanel(type = 'pills',
  tabPanel(h4('Distribution Function'),  metricsgraphicsOutput("logC",height = "550px")),
  tabPanel(h4('Density'),                metricsgraphicsOutput("logP",height = "600px")),
  tabPanel(h4('Survival'),               metricsgraphicsOutput("logR",height = "600px")),
  tabPanel(h4('Hazard'),                 metricsgraphicsOutput("logh",height = "600px")),
  tabPanel(h4('Cumulative Hazard'),      metricsgraphicsOutput("logH",height = "600px")),
  tabPanel(h4('Quantile'),               metricsgraphicsOutput("logQ",height = "600px"))))))))
