ui = navbarPage(title = 'Location-Scale Family',
                collapsible = T, 
                position = 'fixed-top',
                theme  = teachingApps::add_theme(getShinyOption('theme')),
                header = teachingApps::add_css(),
                footer = teachingApps::add_logo(),


tabPanel('Overview',
         mainPanel(uiOutput('overview'), 
                   class = 'ta-text', 
                   width = 12)),
#############################
  tabPanel('Exponential',
#############################
fluidRow(
  column(width = 12,
     mainPanel(uiOutput('expfunc'), 
               class = 'ta-text', width = '100%'))),

fluidRow(
  column(width = 12,
     mainPanel(uiOutput('expprops'), 
                     class = 'ta-text', width = '100%'))),

fluidRow(
  column(width = 12, 'Interactive Shiny App'),
  column(width = 3,
  sidebarPanel(width = '100%', 
  sliderInput("rangee", 
              label = "Range:",
              min = 0, 
              max = 50, 
              value = c(0,20)),
  hr(),
  sliderInput("theta", 
              label = HTML("Scale (&theta;)"),
              min = .5, 
              max = 10, 
              step = .5, 
              value = 1,
              animate = T),
  hr(),
  sliderInput("gamma", 
              label = HTML("Location (&gamma;)"),
              min = 0, 
              max = 15, 
              step = 1, 
              value = 0,
              animate = T))),

column(width = 9,
    mainPanel(width = '100%', 
tabsetPanel(type = 'pills',
  tabPanel('Distribution Function',
           metricsgraphicsOutput("expC",height = "600px")),
  tabPanel('Density',
           metricsgraphicsOutput("expP",height = "600px")),
  tabPanel('Survival',
           metricsgraphicsOutput("expR",height = "600px")),
  tabPanel('Hazard',
           metricsgraphicsOutput("exph",height = "600px")),
  tabPanel('Cumulative Hazard',
           metricsgraphicsOutput("expH",height = "600px")),
  tabPanel('Quantile',
           metricsgraphicsOutput("expQ",height = "600px"))))))),

#######################
tabPanel('Normal',
#######################
fluidRow(
  column(width = 12,
     mainPanel(uiOutput('norfunc'), 
               class = 'ta-text', width = '100%'))),

fluidRow(
  column(width = 12,
     mainPanel(uiOutput('norprops'), 
                     class = 'ta-text', width = '100%'))),

fluidRow(
  column(width = 12, 'Interactive Shiny App'),
  column(width = 3,
  sidebarPanel(width = '100%', 
  sliderInput("range.n", 
              label = "Range",
              min = -20, 
              max = 20, 
              value = c(-4,4)),
  hr(),
  sliderInput("mu.n", 
              label = HTML("Mean (&mu;)"),
              min = -3, 
              max = 3, 
              step = 0.5, 
              value = 0,
              animate = T),
  hr(),
  sliderInput("sig.n", 
              label = HTML("Std Dev (&sigma;)"),
              min = 0.5, 
              max = 5, 
              step = 0.5, 
              value = 1,
              animate = T))),

column(width = 9,
    mainPanel(width = '100%', 
tabsetPanel(type = 'pills',
  tabPanel('Distribution Function',
           metricsgraphicsOutput("norC",height = "600px")),
  tabPanel('Density',
           metricsgraphicsOutput("norP",height = "600px")),
  tabPanel('Survival',
           metricsgraphicsOutput("norR",height = "600px")),
  tabPanel('Hazard',
           metricsgraphicsOutput("norh",height = "600px")),
  tabPanel('Cumulative Hazard',
           metricsgraphicsOutput("norH",height = "600px")),
  tabPanel('Quantile',
           metricsgraphicsOutput("norQ",height = "600px"))))))),

#######################################
tabPanel('SEV',
#######################################
fluidRow(
  column(width = 12,
     mainPanel(uiOutput('sevfunc'), 
               class = 'ta-text', width = '100%'))),

fluidRow(
  column(width = 12,
     mainPanel(uiOutput('sevprops'), 
               class = 'ta-text', width = '100%'))),

fluidRow(
  column(width = 12, 'Interactive Shiny App'),
  column(width = 3,
  sidebarPanel(width = '100%', 
  sliderInput("range.s", 
              label = "Range",
              min = -20, 
              max = 20, 
              value = c(-6,6)),
  hr(),
  sliderInput("mu.sev", 
              label = HTML("Mean (&mu;)"),
              min = -3, 
              max = 3, 
              step = 0.5, 
              value = 0,
              animate = T),
  hr(),
  sliderInput("sig.sev", 
              label = HTML("Std Dev (&sigma;)"),
              min = 1, 
              max = 10, 
              step = 0.5, 
              value = 1,
              animate = T))),

column(width = 9,
    mainPanel(width = '100%', 
tabsetPanel(type = 'pills',
  tabPanel('Distribution Function',
           metricsgraphicsOutput("sevC",height = "600px")),
  tabPanel('Density',
           metricsgraphicsOutput("sevP",height = "600px")),
  tabPanel('Survival',
           metricsgraphicsOutput("sevR",height = "600px")),
  tabPanel('Hazard',
           metricsgraphicsOutput("sevh",height = "600px")),
  tabPanel('Cumulative Hazard',
           metricsgraphicsOutput("sevH",height = "600px")),
  tabPanel('Quantile',
           metricsgraphicsOutput("sevQ",height = "600px"))))))),

######################################
tabPanel('LEV',
######################################
fluidRow(
  column(width = 12,
     mainPanel(uiOutput('levfunc'), 
               class = 'ta-text', width = '100%'))),

fluidRow(
  column(width = 12,
     mainPanel(uiOutput('levprops'), 
               class = 'ta-text', width = '100%'))),

fluidRow(
  column(width = 12, 'Interactive Shiny App'),
  column(width = 3,
  sidebarPanel(width = '100%', 
  sliderInput("range.lev", 
              label = "Range",
              min = -20, 
              max = 20, 
              value = c(-6,6)),
  hr(),
  sliderInput("mu.lev", 
              label = HTML("Mean (&mu;)"),
              min = -3, 
              max = 3, 
              step = 0.5, 
              value = 0,
              animate = T),
  hr(),
  sliderInput("sig.lev", 
              label = HTML("Std Dev (&sigma;)"),
              min = 1, 
              max = 10, 
              step = 0.5, 
              value = 1,
              animate = T))),

column(width = 9,
    mainPanel(width = '100%', 
tabsetPanel(type = 'pills',
  tabPanel('Distribution Function',
           metricsgraphicsOutput('levC',height = "600px")),
  tabPanel('Density',
           metricsgraphicsOutput('levP',height = "600px")),
  tabPanel('Survival',
           metricsgraphicsOutput('levR',height = "600px")),
  tabPanel('Hazard',
           metricsgraphicsOutput('levh',height = "600px")),
  tabPanel('Cumulative Hazard',
           metricsgraphicsOutput('levH',height = "600px")),
  tabPanel('Quantile',
           metricsgraphicsOutput('levQ',height = "600px"))))))),

######################################
tabPanel('Logistic',
######################################
fluidRow(
  column(width = 12,
     mainPanel(uiOutput('logisfunc'), 
               class = 'ta-text', width = '100%'))),

fluidRow(
  column(width = 12,
     mainPanel(uiOutput('logisprops'), 
               class = 'ta-text', width = '100%'))),

fluidRow(
  column(width = 12, 'Interactive Shiny App'),
  column(width = 3,
  sidebarPanel(width = '100%', 
  sliderInput("range.l", 
              label = "Range",
              min = -20, 
              max = 20, 
              value = c(-4,4)),
  hr(),
  sliderInput("mu.l", 
              label = HTML("Mean (&mu;)"),
              min = -3, 
              max = 3, 
              step = 0.5, 
              value = 0,
              animate = T),
  hr(),
  sliderInput("sig.l", 
              label = HTML("Std Dev (&sigma;)"),
              min = 0.5, 
              max = 5, 
              step = 0.5, 
              value = 1,
              animate = T))),

column(width = 9,
    mainPanel(width = '100%', 
tabsetPanel(type = 'pills',
  tabPanel('Distribution Function',
           metricsgraphicsOutput("logC",height = "550px")),
  tabPanel('Density',
           metricsgraphicsOutput("logP",height = "600px")),
  tabPanel('Survival',
           metricsgraphicsOutput("logR",height = "600px")),
  tabPanel('Hazard',
           metricsgraphicsOutput("logh",height = "600px")),
  tabPanel('Cumulative Hazard',
           metricsgraphicsOutput("logH",height = "600px")),
  tabPanel('Quantile',
           metricsgraphicsOutput("logQ",height = "600px"))))))))
