ui = fluidPage(theme = teachingApps::add_theme(getShinyOption("theme")), 
               teachingApps::add_css(),
               
sidebarLayout(
  sidebarPanel(width = 3, 
    sliderInput("m.hyp", 
                label = "Number of Success States (m)",
                min = .05, 
                max = 1, 
                step=.05, 
                value = .05,
                animate = TRUE),
    sliderInput("n.hyp", 
                label = "Number of Failure States (n)",
                min = 0, 
                max = 50, 
                step = 1,
                value = 2),
    sliderInput("k.hyp", 
                label = "Number of draws (k)",
                min = .05, 
                max = 1, 
                step = .05, 
                value = .05,
                animate = TRUE)), 

mainPanel(width = 9, 
          tabsetPanel(type = "pills", 
          tabPanel("Distribution Function", 
                   metricsgraphicsOutput("hypC", height = "600px")), 
          tabPanel("Mass",
                   metricsgraphicsOutput("hypP", height = "600px")), 
          tabPanel("Survival", 
                   metricsgraphicsOutput("hypR", height = "600px")), 
          tabPanel("Hazard", 
                   metricsgraphicsOutput("hyph", height = "600px")), 
          tabPanel("Cumulative Hazard", 
                   metricsgraphicsOutput("hypH", height = "600px")),
          tabPanel("Quantile", 
                   metricsgraphicsOutput("hypQ", height = "600px")))))) 
