---
title: "Vignette Title"
author: "Vignette Author"
date: "`r Sys.Date()`"
output: 
  rmarkdown::html_vignette:
    css: my-vignette.css
    fig_caption: yes
vignette: >
  %\VignetteIndexEntry{teachingApps-overview}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

teachingApps is a soon-to-be-published software package for crowd-sourcing the creation of math & stats-based web apps. The goal of the package is to make teaching and learning complex math/stats concepts really fast and really easy.

In this talk Maj Jason Freels (ENV) presents some of the 135 apps that have already been built into the package and outlines how these apps can be used to:
 
A) Present four layers of information simultaneously:

    1) Math/Stats concepts through interactive visualizations

    2) Computer programming skills - with R (Python coming soon)

    3) LaTeX equation typesetting with <a target=' ' href='https://www.mathjax.org/'><b>MathJax</b></a>

    4) App development using HTML5, CSS3, and <a target=' ' href='http://shiny.rstudio.com/'><b>Shiny</b></a><br/>

B) Integrate into existing lecture materials (in-res & distance learning)

    + PowerPoint/Prezi/Keynote presentations

    + PDF/Beamer presentations

    + HTML presentations

    + Video Presentations

C) Combine teaching materials from SME's

    + Text

    + Equations

    + Images/Videos

    + Code

    + Shiny Apps

D) Ensure math/stat content is presented consistently across courses 

Math and statistics (math/stat) are part of nearly every course 
in any technical degree program. In many of these courses, math/stat is not the 
primary subject but is used to support a student's understanding of a physical concept. 
physics, and chemistry.  learning are not courses
in math/stats \code{LaTeX, code} \code{reduce overlap}.

teachingApps is a software package for crowd-sourcing the creation of 
web apps to make teaching math/stats faster and easier. The goal
of the package is to help both students and instructors by 

A) Presenting four layers of information simultaneously:

   - Math/Stats concepts through interactive visualizations
- Computer programming skills - with R (Python coming soon)
- LaTeX equation typesetting with <a target=' ' href='https://www.mathjax.org/'>MathJax</a>
- App development using HTML5, CSS3, and <a target=' ' href='http://shiny.rstudio.com/'>Shiny

The teachingApps package was initially created to help statistics
instructors integrate JavaScript-based visualizations into their existing
materials.  To date, more than 130 completed apps have been built into the 
package to explain/visualize topics such as

- maximum likelihood estimation
- confidence interval construction
- random variable sigma-algebra
- Explained error in linear regression
- Central Limit Theorem
- Censored and Trucated data
- Over 20 probability distributions  


open-source R & Python
interactive, crowd-source math/stat

teachingApps brings several packages together to make it possible provide best 
and teach
 collection of interactive applications designed to help instructors explain
several math/stat conceptscan include in their existing teaching 
materials to describe and visualize math/stat concepts.  More importantly, teachingApps 
is an open-source infrastructure allowing subject matter experts to collectively
their content to improve the quality of each app.

merge content, javascript applications, available anywhere, consistent explanations
