ui = fluidPage(theme = add_theme(getShinyOption('theme')), 
               add_css(),

sidebarLayout(
sidebarPanel(width = 3,
  selectInput("dist1", 
              label = "Distribution (Left)",
              choices = c("Exponential",
                          "Normal",
                          "SEV",
                          "Logistic",
                          "LEV"), 
              selected = "SEV"),
  selectInput("axis1", 
              label = "Axis (Left)",
              choices = c("True Axis",
                          "Transformed Axis"), 
              selected = "True Axis"),
  selectInput("dist2", 
              label = "Distribution (Right)",
              choices = c("Exponential",
                          "Normal",
                          "SEV",
                          "Logistic",
                          "LEV"), 
              selected = "SEV"),
  selectInput("axis2", 
              label = "Axis (Right)",
              choices = c("True Axis",
                          "Transformed Axis"), 
              selected = "Transformed Axis")),

mainPanel(plotOutput("compare", height = "600px"), width = 9)))
