ui = fluidPage(theme = teachingApps::add_theme(getShinyOption("theme")), 
               teachingApps::add_css(),

sidebarLayout(
  sidebarPanel(width = 3, 
  hr(),
  sliderInput("range.l", 
              label = "Range",
              min = -20, 
              max = 20, 
              value = c(-4,4)),
  hr(),
  sliderInput("mu.l", 
              label = HTML("Mean (&mu;)"),
              min = -3, 
              max = 3, 
              step = 0.5, 
              value = 0, 
              animate = T),
  hr(),
  sliderInput("sig.l", 
              label = HTML("Std Dev (&sigma;)"),
              min = 0.5, 
              max = 5, 
              step = 0.5, 
              value = 1, 
              animate = T)),

mainPanel(width = 9,
 tabsetPanel(type = 'pills',
  tabPanel('Distribution Function',
           metricsgraphicsOutput("logC",height = "550px")),
  tabPanel('Density',
           metricsgraphicsOutput("logP",height = "600px")),
  tabPanel('Survival',
           metricsgraphicsOutput("logR",height = "600px")),
  tabPanel('Hazard',
           metricsgraphicsOutput("logh",height = "600px")),
  tabPanel('Cumulative Hazard',
           metricsgraphicsOutput("logH",height = "600px")),
  tabPanel('Quantile',
           metricsgraphicsOutput("logQ",height = "600px"))))))
