ui = fluidPage(theme = teachingApps::add_theme(getShinyOption("theme")), 
               teachingApps::add_css(),
               
sidebarLayout(
  sidebarPanel(width = 3, 
  hr(), 
  sliderInput("range.geom", 
              label = "Range",
              min = 0, 
              max = 50, 
              step = 1,
              value = c(0,10)),
  hr(), 
  sliderInput("prob.geom", 
              label = "Probability",
              min = .05, 
              max = 1, 
              step = .05, 
              value = .05,
              animate = TRUE)), 

mainPanel(width = 9, 
          tabsetPanel(type = "pills", 
          tabPanel("Distribution Function", 
                   metricsgraphicsOutput("geomC", height = "600px")), 
          tabPanel("Mass",
                   metricsgraphicsOutput("geomP", height = "600px")), 
          tabPanel("Survival", 
                   metricsgraphicsOutput("geomR", height = "600px")), 
          tabPanel("Hazard", 
                   metricsgraphicsOutput("geomh", height = "600px")), 
          tabPanel("Cumulative Hazard", 
                   metricsgraphicsOutput("geomH", height = "600px")),
          tabPanel("Quantile", 
                   metricsgraphicsOutput("geomQ", height = "600px")))))) 
