ui = fluidPage(theme = teachingApps::add_theme(getShinyOption("theme")), 
               teachingApps::add_css(),
               
sidebarLayout(
  sidebarPanel(width = 3,
  hr(),
  sliderInput("range.ln", 
              label = "Range:",
              min = 0, 
              max = 50, 
              value = c(0,20)),
  hr(),
  sliderInput("mu.ln", 
              label = HTML("Log[Mean] (ln[&mu;])"),
              min = 0, 
              max = 10, 
              step = 0.5, 
              value = 4, 
              animate = T),
  hr(),
  sliderInput("sig.ln", 
              label = HTML("log[Std Dev] (ln[&sigma;])"),
              min = .5, 
              max = 10, 
              step = 0.5, 
              value = 1, 
              animate = T)),

mainPanel(width = 9,
 tabsetPanel(type = 'pills',
  tabPanel('Distribution Function',
           metricsgraphicsOutput("lnorC",height = "600px")),
  tabPanel('Density',
           metricsgraphicsOutput("lnorP",height = "600px")),
  tabPanel('Survival',
           metricsgraphicsOutput("lnorR",height = "600px")),
  tabPanel('Hazard',
           metricsgraphicsOutput("lnorh",height = "600px")),
  tabPanel('Cumulative Hazard',
           metricsgraphicsOutput("lnorH",height = "600px")),
  tabPanel('Quantile',
           metricsgraphicsOutput("lnorQ",height = "600px"))))))
