---
output: html_document
---

### Example 1.2 - Integrated Circuit Life Test (Meeker, 1987)

- Motivation for the study

    + Company A is shipping products with defective integrated circuits (IC)

    + The company wants to ID which products contain defective IC's and remove them from the population of items to be shipped

    + Identifying the defective products requires testing them to simulate their first year of operation (process called burn-in)

    + Very little time is available to conduct the burn-in inspection

    + Since temperature & humidity affect the service life of IC's exposing the units to elevated temperature & humidity may help speed the burn-in inspection

    + However, Company A is concerned that this 'accelerated' burn-in may not produce meaningful information
    
- Study objectives

    - Estimate the probability of IC's failing before 100 hours

    - Estimate the hazard function at 100 hours

    - Estimate the required burn-in time to remove the majority of the defective units

- Data set (Table 1.2) `lfp1370`

    - Lifetimes of $n = 4156$ integrated circuits (IC's) 

    - IC's were exposed to $80^{o}C$ and $80\%$ relative humidity until failure

    - The test was stopped after 1370 hours (28 failures were observed, the rest were right censored)
