---
output: html_document
---

### Liebling & Zelen - Ball Bearing Fatigue Test

- Motivation

    + This example introduce the concept of estimating failure probability from <red>singly right censored data</red> using the binomial distribution

    + Recall the `heatexchanger` data set presented in Example 1.5

    + Suppose we inspect $100$ heat exchanger tubes at Plant 1 only, and assign each tube a value $d_i$, where
    
$$d_i=\begin{cases}1&\mbox{if the tube has failed}\\\\ 0&\mbox{if the tube has not failed}\end{cases}$$

- Data set `subset(SMRD::heatexchanger, plant=='Plant1')`

    + The inspection data are $100$ binary observations from a Bernoulli RV

    + The Bernoulli parameter $p \in [0,1]$ represents the probability of observing a "success" <orange>in this case a success is actually a failure</orange>
    
    + The trials are mutually independent (i.e. The probability of "success" is the same for each observation )
    
- The <u>outcome</u> of this inspection procedue (the total number of observed "successes") is a single observation from a binomial RV with parameters $n, p$

    + Recall, the binomial distribution models the probability of observing $x$ successes in $n$ trials where the probability of success for each trial is $p$
    
    + The probability mass function for a $BIN(n,p)$ random variable is 

$$f(x;p,n) = \left( \begin{array}{c} n \\ x \end{array} \right)(p)^{x}(1 - p)^{(n-x)} \;\;\;\;\;\; \mbox{for x = 0, 1, 2,..., n}$$

- where 

    + $x$ is the number of observed "successes" (failures in this case)

    + $n$ is the total sample size

    + $p$ is the true (but unknown) long-run probability that a unit will fail

- A nonparametric estimator for $F(t)$ is the binomial parameter $p$

<div class="notes">As discussed in Chapter 2, $\pi_{i}$ represents the multinomial probability that a failure will occur in interval $i$.</div>

$$\hat{p}_{_{MLE}}=\frac{x}{n}$$

