ui = fluidPage(theme = teachingApps::add_theme(getShinyOption("theme")), 
               teachingApps::add_css(),

sidebarLayout(
  sidebarPanel(width = 3, 
  hr(),
  sliderInput("range.s", 
              label = "Range",
              min = -20, 
              max = 20, 
              value = c(-6,6)),
  hr(),
  sliderInput("mu.sev", 
              label = HTML("Mean (&mu;)"),
              min = -3, 
              max = 3, 
              step = 0.5, 
              value = 0, 
              animate = T),
  hr(),
  sliderInput("sig.sev", 
              label = HTML("Std Dev (&sigma;)"),
              min = 1, 
              max = 10, 
              step = 0.5, 
              value = 1, 
              animate = T)),

mainPanel(width = 9,
 tabsetPanel(type = 'pills',
  tabPanel('Distribution Function',
           metricsgraphicsOutput("sevC",height = "600px")),
  tabPanel('Density',
           metricsgraphicsOutput("sevP",height = "600px")),
  tabPanel('Survival',
           metricsgraphicsOutput("sevR",height = "600px")),
  tabPanel('Hazard',
           metricsgraphicsOutput("sevh",height = "600px")),
  tabPanel('Cumulative Hazard',
           metricsgraphicsOutput("sevH",height = "600px")),
  tabPanel('Quantile',
           metricsgraphicsOutput("sevQ",height = "600px"))))))
