ui = fluidPage(theme = teachingApps::add_theme(getShinyOption("theme")), 
               teachingApps::add_css(),
              
sidebarLayout(
  sidebarPanel(width = 3, 
  hr(),
  sliderInput("range.n", 
              label = "Range",
              min = -20, 
              max = 20, 
              value = c(-4,4)),
  hr(),
  sliderInput("mu.n", 
              label = HTML("Mean (&mu;)"),
              min = -3, 
              max = 3, 
              step = 0.5, 
              value = 0, 
              animate = T),
  hr(),
  sliderInput("sig.n", 
              label = HTML("Std Dev (&sigma;)"),
              min = 0.5, 
              max = 5, 
              step = 0.5, 
              value = 1, 
              animate = T)),

mainPanel(width = 9,
 tabsetPanel(type = 'pills',
  tabPanel('Distribution Function',
           metricsgraphicsOutput("norC",height = "600px")),
  tabPanel('Density',
           metricsgraphicsOutput("norP",height = "600px")),
  tabPanel('Survival',
           metricsgraphicsOutput("norR",height = "600px")),
  tabPanel('Hazard',
           metricsgraphicsOutput("norh",height = "600px")),
  tabPanel('Cumulative Hazard',
           metricsgraphicsOutput("norH",height = "600px")),
  tabPanel('Quantile',
           metricsgraphicsOutput("norQ",height = "600px"))))))
