library(teachingApps)
library('metricsgraphics')

ui = navbarPage(title = 'Beta Distribution',
                collapsible = T, 
                position = 'fixed-top',
                theme = shinythemes::shinytheme(theme = getShinyOption("theme")),
                header = tags$head(includeCSS(getShinyOption("css"))),
                footer = HTML(teachingApps::teachingApp(getShinyOption("appName"))),
                
tabPanel(h4('Shiny App'),
sidebarLayout(
  sidebarPanel(width = 3, 
sliderInput("shape1", 
            label = h2(HTML("Shape Parameter (&alpha;)")),
            min = .5, 
            max = 10, 
            step=.5, 
            value = 2,
            animate=TRUE),
sliderInput("shape2", 
            label = h2(HTML("Shape Parameter (&beta;)")),
            min = .5, 
            max = 10, 
            step = .5,
            value = .5),
sliderInput("scale.beta", 
            label = h2("Scale Parameter (d)"),
            min = 1, 
            max = 20, 
            step = 1, 
            value = 1,
            animate=TRUE),
sliderInput("loc.beta", 
            label = h2("Location Parameter (c)"),
            min = 0, 
            max = 10, 
            step = .5, 
            value = 0,
            animate=TRUE)), 

mainPanel(width = 9, 
          tabsetPanel(type = "pills", 
          tabPanel(h4("Distribution Function"), 
                   metricsgraphicsOutput("betaC", height = "600px")), 
          tabPanel(h4("Mass"),
                   metricsgraphicsOutput("betaP", height = "600px")), 
          tabPanel(h4("Survival"), 
                   metricsgraphicsOutput("betaR", height = "600px")), 
          tabPanel(h4("Hazard"), 
                   metricsgraphicsOutput("betah", height = "600px")), 
          tabPanel(h4("Cumulative Hazard"), 
                   metricsgraphicsOutput("betaH", height = "600px")),
          tabPanel(h4("Quantile"), 
                   metricsgraphicsOutput("betaQ", height = "600px")))))),

tabPanel(h4('Distribution Functions'),
         mainPanel(uiOutput('betafunc'), class = 'shiny-text-output', width = 12)),

tabPanel(h4('Distribution Properties'),
         mainPanel(uiOutput('betaprops', class = 'shiny-text-output'), width = 12)))
