---
output: html_document
---

### Package Background

- _SMRD_ was derived from an <a target=' ' href='http://stat.ethz.ch/~www/SandR.html'>S-Plus</a> software package called <a target=' ' href='http://www.public.iastate.edu/~splida/'>SPLIDA</a> (<u>S</u>-<u>P</u>lus <u>LI</u>fe <u>D</u>ata <u>A</u>nalysis) by [Dr. Bill Meeker](http://www.public.iastate.edu/~wqmeeker/homepage.html)

    + Dr Meeker wrote a large collection of FORTRAN subroutines to during his career at Bell Labs and Iowa State University 

    + With the help of Dr. Luis Escobar, Dr. Meeker created the _SPLIDA_ package by porting the FORTRAN code to S-Plus

    + The _SPLIDA_ package serves as the companion software for <a target=' 'href='https://www.amazon.com/Statistical-Methods-Reliability-William-Meeker/dp/0471143286'>Statistical Methods for Reliability Data</a> 1^st ed.

    + GUI interface - plots and results were difficult to customize

- Meeker later translated _SPLIDA_ into R and renamed the package _RSplida_

    + R is an updated implementation of S/S-Plus language

    + Translation was rushed and incomplete - couldn't be installed as a traditional R package 

    + Retained many of the 'GUI' limitations of _SPLIDA_

    + Couldn't be used any IDE (i.e. RStudio, Eclipse, etc.)
    
    + Not user-friendly

- In 2014, Freels began updating _RSplida_ as an R package

    + Initially named _meekR_, then renamed _SMRD_

    + _SMRD_ will be published to the CRAN in 2017 along with the 2^nd edition of Statistical Methods for Reliability Data 

    + Installing _SMRD_ requires the installation of two dependencies `plot3D` and `FSA`

    + In the R console, run `install.packages(c('plot3D','FSA'))`
