---
output: html_document
---

### Package Features

- _SMRD_ was created to estimate various reliability measures for failure data with:

    + Failure times with multiple failure modes

    + Censored failure times (right, left, and interval censoring)

    + Truncated failure times (right, left, and interval truncation)

    + Failure times with explanatory variables (normal, Weibull, and logistic regression)

    + Repeated measures degradation data

    + Repairable system failures (recurring events)

    + Physical degradation

    + Failure times with prior information (Bayesian reliability)

    + Reliability growth test data

    + Reliability test simulations

- _SMRD_ was built for use with Markdown documents and presentations 

    + Allows for a seamless workflow to create papers & presentations incredibly fast 
    
    + The package can be used to create high-quality plots with a single line of code 

    + Turn results into $\LaTeX$ tables instantly (with the <a target=' ' href='https://cran.r-project.org/web/packages/xtable/index.html'>xtable</a>, <a target=' ' href='https://cran.r-project.org/web/packages/stargazer/index.html'>stargazer</a>, and <a target=' ' href='https://cran.r-project.org/web/packages/pander/index.html'>pander</a> packages)

    + Easily create interactive content (with the <a target=' ' href='https://cran.r-project.org/web/packages/shiny/index.html'>shiny</a>, <a target=' ' href='https://cran.r-project.org/web/packages/htmlwidgets/index.html'>htmlwidgets<a/>, and <a target=' ' href='https://cran.r-project.org/web/packages/ggvis/index.html'>ggvis<a/> packages)

    + Over 120 data sets have been built into the package, see list using `data(package = "SMRD")`

### Package Features

- _SMRD_ was created to estimate various reliability measures for failure data with:

    + Failure times with multiple failure modes

    + Censored failure times (right, left, and interval censoring)

    + Truncated failure times (right, left, and interval truncation)

    + Failure times with explanatory variables (normal, Weibull, and logistic regression)

    + Repeated measures degradation data

    + Repairable system failures (recurring events)

    + Physical degradation

    + Failure times with prior information (Bayesian reliability)

    + Reliability growth test data

    + Reliability test simulations

- _SMRD_ was built for use with Markdown documents and presentations 

    + Allows for a seamless workflow to create papers & presentations incredibly fast 
    
    + The package can be used to create high-quality plots with a single line of code 

    + Turn results into $\LaTeX$ tables instantly (with the <a target=' ' href='https://cran.r-project.org/web/packages/xtable/index.html'>xtable</a>, <a target=' ' href='https://cran.r-project.org/web/packages/stargazer/index.html'>stargazer</a>, and <a target=' ' href='https://cran.r-project.org/web/packages/pander/index.html'>pander</a> packages)

    + Easily create interactive content (with the <a target=' ' href='https://cran.r-project.org/web/packages/shiny/index.html'>shiny</a>, <a target=' ' href='https://cran.r-project.org/web/packages/htmlwidgets/index.html'>htmlwidgets<a/>, and <a target=' ' href='https://cran.r-project.org/web/packages/ggvis/index.html'>ggvis<a/> packages)

    + Over 120 data sets have been built into the package, see list using `data(package = "SMRD")`

