ui = fluidPage(theme = add_theme(getShinyOption('theme')), 
               add_css(),

sidebarLayout(
    sidebarPanel(width = 3,
       sliderInput('ttt', 
                   'Available Test Time', 
                    min = 100, 
                    max = 1000, 
                    step = 10, 
                    value = 400),
       sliderInput('fails', 
                   'Failures Allowed', 
                    min = 0, 
                    max = 30, 
                    step = 1, 
                    value = 1),
       sliderInput('thresh', 
                   'Threshold MTBF', 
                    min = 10, 
                    max = 500, 
                    step = 5, 
                    value = 40),
       sliderInput('objective', 
                   'Objective MTBF', 
                    min = 10, 
                    max = 500, 
                    step = 5, 
                    value = 70),
       sliderInput('contract', 
                   'Contract MTBF', 
                    min = 10, 
                    max = 500, 
                    step = 5, 
                    value = 90)),
  mainPanel(plotlyOutput('mtbf', height = '650px'),width = 9)))

