ui = fluidPage(theme = add_theme(getShinyOption('theme')), 
               add_css(),
               
sidebarLayout(
  sidebarPanel(width = 3, 
     hr(), 
     sliderInput("range.bin", 
                 label = "Range:",
                 min = 0, 
                 max = 50, 
                 step = 1,
                 value = c(0,10)),
     hr(),
     sliderInput("n.bin", 
                 label = "Observations",
                 min = 0, 
                 max = 50, 
                 step = 1, 
                 value = 5), 
     hr(), 
     sliderInput("prob.bin", 
                 label = "Probability",
                 min = .05, 
                 max = 1, 
                 step=.05, 
                 value = .05,
                 animate=TRUE)), 

   mainPanel(width = 9, 
       tabsetPanel(type = "pills", 
             tabPanel("Distribution Function", 
                      metricsgraphicsOutput("binC")), 
             tabPanel("Density",
                      metricsgraphicsOutput("binP")), 
             tabPanel("Survival", 
                      metricsgraphicsOutput("binR")), 
             tabPanel("Hazard", 
                      metricsgraphicsOutput("binh")), 
             tabPanel("Cumulative Hazard", 
                      metricsgraphicsOutput("binH")),
             tabPanel("Quantile", 
                      metricsgraphicsOutput("binQ"))))))
