ui = fluidPage(theme = teachingApps::add_theme(getShinyOption("theme")), 
               teachingApps::add_css(),
               
sidebarLayout(
  sidebarPanel(width = 3, 
     hr(), 
     sliderInput("range.bin", 
                 label = "Range:",
                 min = 0, 
                 max = 50, 
                 step = 1,
                 value = c(0,10)),
     hr(),
     sliderInput("n.bin", 
                 label = "Observations",
                 min = 0, 
                 max = 50, 
                 step = 1, 
                 value = 5), 
     hr(), 
     sliderInput("prob.bin", 
                 label = "Probability",
                 min = .05, 
                 max = 1, 
                 step=.05, 
                 value = .05,
                 animate=TRUE)), 

   mainPanel(width = 9, 
       tabsetPanel(type = "pills", 
             tabPanel("Distribution Function", 
                      metricsgraphicsOutput("binC", height = "600px")), 
             tabPanel("Density",
                      metricsgraphicsOutput("binP", height = "600px")), 
             tabPanel("Survival", 
                      metricsgraphicsOutput("binR", height = "600px")), 
             tabPanel("Hazard", 
                      metricsgraphicsOutput("binh", height = "600px")), 
             tabPanel("Cumulative Hazard", 
                      metricsgraphicsOutput("binH", height = "600px")),
             tabPanel("Quantile", 
                      metricsgraphicsOutput("binQ", height = "600px"))))))
