ui = fluidPage(theme = teachingApps::add_themes(getShinyOption("theme")), 
               teachingApps::add_styles(),
               
mainPanel(width = 12,
   tabsetPanel(type = 'pills',
     tabPanel(h4('Data Analysis'),           
              visNetworkOutput("stats",height = "600px")),
     tabPanel(h4('Programming'),             
              visNetworkOutput("coding",height = "600px")),
     tabPanel(h4('Data Munging'),            
              visNetworkOutput("munging",height = "600px")),
     tabPanel(h4('Reproducible Research'),   
              visNetworkOutput("reproduce",height = "600px")),
     tabPanel(h4('Web Development'),         
              visNetworkOutput("webdev",height = "600px")),
     tabPanel(h4('This Course'),             
              visNetworkOutput("stat687",height = "600px")))))
