ui = fluidPage(theme = teachingApps::add_theme(getShinyOption("theme")), 
               teachingApps::add_css(),
               
sidebarLayout(
  sidebarPanel(width = 3, 
hr(), 
sliderInput("range.pois", 
            label = "Range",
            min = 0, 
            max = 50, 
            step = 1,
            value = c(0,10)),
hr(), 
sliderInput("lamb.pois", 
            label = "Lambda",
            min = .5, 
            max = 10, 
            step=.5, 
            value = .5,
            animate=TRUE)), 

mainPanel(width = 9, 
          tabsetPanel(type = "pills", 
          tabPanel("Distribution Function", 
                   metricsgraphicsOutput("poisC", height = "600px")), 
          tabPanel("Mass",
                   metricsgraphicsOutput("poisP", height = "600px")), 
          tabPanel("Survival", 
                   metricsgraphicsOutput("poisR", height = "600px")), 
          tabPanel("Hazard", 
                   metricsgraphicsOutput("poish", height = "600px")), 
          tabPanel("Cumulative Hazard", 
                   metricsgraphicsOutput("poisH", height = "600px")),
          tabPanel("Quantile", 
                   metricsgraphicsOutput("poisQ", height = "600px"))))))
