ui = fluidPage(theme = add_theme(getShinyOption('theme')), 
               add_css(),
               
sidebarLayout(
  sidebarPanel(width = 3, 
hr(), 
sliderInput("range.pois", 
            label = "Range",
            min = 0, 
            max = 50, 
            step = 1,
            value = c(0,10)),
hr(), 
sliderInput("lamb.pois", 
            label = "Lambda",
            min = .5, 
            max = 10, 
            step=.5, 
            value = .5,
            animate=TRUE)), 

mainPanel(width = 9, 
          tabsetPanel(type = "pills", 
          tabPanel("Distribution Function", 
                   metricsgraphicsOutput("poisC")), 
          tabPanel("Mass",
                   metricsgraphicsOutput("poisP")), 
          tabPanel("Survival", 
                   metricsgraphicsOutput("poisR")), 
          tabPanel("Hazard", 
                   metricsgraphicsOutput("poish")), 
          tabPanel("Cumulative Hazard", 
                   metricsgraphicsOutput("poisH")),
          tabPanel("Quantile", 
                   metricsgraphicsOutput("poisQ"))))))
