# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' The Birmbaum-Saunders Distribution
#' @description Density, distribution function, quantile function and 
#'              random generation for the BISA distribution with location
#'              \code{loc} and scale \code{scale}.
#' @export
#' @rdname bisa
#' @param p Vector of probabilities
#' @param x Vector of quantiles
#' @param q Vector of quantiles
#' @param n Number of observations
#' @param shape Shape parameter
#' @param scale Scale parameter
qbisa <- function(p, shape, scale = 1) {
    .Call('teachingApps_qbisa', PACKAGE = 'teachingApps', p, shape, scale)
}

#' @export
#' @rdname bisa
pbisa <- function(q, shape, scale = 1) {
    .Call('teachingApps_pbisa', PACKAGE = 'teachingApps', q, shape, scale)
}

dlbisa <- function(z, shape) {
    .Call('teachingApps_dlbisa', PACKAGE = 'teachingApps', z, shape)
}

#' @export
#' @rdname bisa
dbisa <- function(x, shape, scale = 1) {
    .Call('teachingApps_dbisa', PACKAGE = 'teachingApps', x, shape, scale)
}

#' @export
#' @rdname bisa
rbisa <- function(n, shape, scale = 1) {
    .Call('teachingApps_rbisa', PACKAGE = 'teachingApps', n, shape, scale)
}

#' The Largest Extreme Value Distribution
#' @description Density, distribution function, quantile function and 
#'              random generation for the LEV distribution with location
#'              \code{loc} and scale \code{scale}.
#' @export
#' @rdname lev
#' @param p Vector of probabilities
#' @param x Vector of quantiles
#' @param q Vector of quantiles
#' @param n Number of observations
#' @param loc Location parameter
#' @param scale Scale parameter
qlev <- function(p, loc = 0, scale = 1) {
    .Call('teachingApps_qlev', PACKAGE = 'teachingApps', p, loc, scale)
}

#' @export
#' @rdname lev
plev <- function(q, loc = 0, scale = 1) {
    .Call('teachingApps_plev', PACKAGE = 'teachingApps', q, loc, scale)
}

#' @export
#' @rdname lev
dlev <- function(x, loc = 0, scale = 1) {
    .Call('teachingApps_dlev', PACKAGE = 'teachingApps', x, loc, scale)
}

#' @export
#' @rdname lev
rlev <- function(n, loc = 0, scale = 1) {
    .Call('teachingApps_rlev', PACKAGE = 'teachingApps', n, loc, scale)
}

likely2 <- function(times, cens, params, maxll) {
    .Call('teachingApps_likely2', PACKAGE = 'teachingApps', times, cens, params, maxll)
}

rcpp_hello_world <- function() {
    .Call('teachingApps_rcpp_hello_world', PACKAGE = 'teachingApps')
}

#' The Smallest Extreme Value Distribution
#' @description Density, distribution function, quantile function and 
#'              random generation for the SEV distribution with location
#'              \code{loc} and scale \code{scale}.
#' @export
#' @rdname sev
#' @param p Vector of probabilities
#' @param x Vector of quantiles
#' @param q Vector of quantiles
#' @param n Number of observations
#' @param loc Location parameter
#' @param scale Scale parameter
qsev <- function(p, loc = 0, scale = 1) {
    .Call('teachingApps_qsev', PACKAGE = 'teachingApps', p, loc, scale)
}

#' @export
#' @rdname sev
psev <- function(q, loc = 0, scale = 1) {
    .Call('teachingApps_psev', PACKAGE = 'teachingApps', q, loc, scale)
}

#' @export
#' @rdname sev
dsev <- function(x, loc = 0, scale = 1) {
    .Call('teachingApps_dsev', PACKAGE = 'teachingApps', x, loc, scale)
}

#' @export
#' @rdname sev
rsev <- function(n, loc = 0, scale = 1) {
    .Call('teachingApps_rsev', PACKAGE = 'teachingApps', n, loc, scale)
}

