# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

likely2 <- function(times, cens, params, maxll) {
    .Call('teachingApps_likely2', PACKAGE = 'teachingApps', times, cens, params, maxll)
}

rcpp_hello_world <- function() {
    .Call('teachingApps_rcpp_hello_world', PACKAGE = 'teachingApps')
}

