ui = fluidPage(theme = teachingApps::add_theme(getShinyOption("theme")), 
               teachingApps::add_css(),

sidebarLayout(
  sidebarPanel(width = 3, 
  hr(),
  sliderInput("range.ll", 
              label = "Range",
              min = 0, 
              max = 50, 
              value = c(0,20)),
  hr(),
  sliderInput("mu.ll", 
              label = HTML("Mean (&mu;)"),
              min = 0.5, 
              max = 10, 
              step = 0.5, 
              value = 0.5, 
              animate = T),
  hr(),
  sliderInput("sig.ll", 
              label = HTML("Std Dev (&sigma;)"),
              min = 0.5, 
              max = 10, 
              step = 0.5, 
              value = 1, 
              animate = T)),

mainPanel(width = 9,
 tabsetPanel(type = 'pills',
  tabPanel('Distribution Function'),  metricsgraphicsOutput("llogC",height = "600px")),
  tabPanel('Density'),                metricsgraphicsOutput("llogP",height = "600px")),
  tabPanel('Survival'),               metricsgraphicsOutput("llogR",height = "600px")),
  tabPanel('Hazard'),                 metricsgraphicsOutput("llogh",height = "600px")),
  tabPanel('Cumulative Hazard'),      metricsgraphicsOutput("llogH",height = "600px")),
  tabPanel('Quantile'),               metricsgraphicsOutput("llogQ",height = "600px"))))))
