ui = fluidPage(theme = add_theme(getShinyOption('theme')), 
               add_css(),

sidebarLayout(
  sidebarPanel(width = 3, 
  hr(),
  sliderInput("range.ll", 
              label = "Range",
              min = 0, 
              max = 50, 
              value = c(0,20)),
  hr(),
  sliderInput("mu.ll", 
              label = HTML("Mean (&mu;)"),
              min = 0.5, 
              max = 10, 
              step = 0.5, 
              value = 0.5, 
              animate = T),
  hr(),
  sliderInput("sig.ll", 
              label = HTML("Std Dev (&sigma;)"),
              min = 0.5, 
              max = 10, 
              step = 0.5, 
              value = 1, 
              animate = T)),

mainPanel(width = 9,
 tabsetPanel(type = 'pills',
  tabPanel('Distribution Function'),  metricsgraphicsOutput("llogC")),
  tabPanel('Density'),                metricsgraphicsOutput("llogP")),
  tabPanel('Survival'),               metricsgraphicsOutput("llogR")),
  tabPanel('Hazard'),                 metricsgraphicsOutput("llogh")),
  tabPanel('Cumulative Hazard'),      metricsgraphicsOutput("llogH")),
  tabPanel('Quantile'),               metricsgraphicsOutput("llogQ"))))))
